### PR TITLE
additional function

### PR DESCRIPTION
**Pull request by Myrkotyn**
Hi. I added a function deleting mails and improve a little bit readme. I use delete function in my own project, it works fine.

### CODE REVIEW

**Comment by xomyaq** [comment]
Hi @Myrkotyn! Thanks for your PR!

Please, can you split it into two pull requests?

**Comment by Myrkotyn** [comment]
Should i split this commits into 2 PRs or i should create 2 PRs into different branches with this commits?

**Comment by xomyaq** [comment]
Let's separate concerns: first PR for documentation and second one for a new method.

**Comment by xomyaq** [comment]
I created two issues: about documentation #4 and deletion method #5. Please note that, current master was significantly changed: I added ESLint config, rewrote tests and module itself.

**Pull request closed without merging**
